### ISSUE TITLE
Better namespacing/scoping

### ISSUE THREAD

**Issue by tmedwards** [SleepyFool-gh/Sleepy-macros#2]
https://github.com/SleepyFool-gh/Sleepy-macros/blob/1fe3103c00dce5ac44abc37708f0d0cca3fcd3f1/p-macro/p-macro.js#L1

To avoid possible collisions with other macros and/or user data, I'd suggest storing the macro's methods and runtime data:

* On the macro's definition—`this.self` in the macro.
* In the scope of an IIFE that the macro is wrapped within.
* If using `setup`, use a unique property, likely prefixed with a character that's not legal in an identifier—e.g., `setup['#Sleepy-macros']` or `setup['#p_macro']`.  Simply using `SS` isn't really that unique.

I generally use the macro's definition in the standard macros, but IIFEs come in handy too.  I'd suggest using one of those methods.

**Comment by SleepyFool-gh** [comment]
I pushed a quick-fix that just changed the namespace to something more unique as suggested for now, will try to get it working with the aux function and variables either on the macro definition or in the handler itself

**Comment by SleepyFool-gh** [comment]
Done, variables and aux functions moved into macro definition, took a bit of single player scrabble though because of the nuanced difference between `this.self` vs `this` in a `handler(...)` vs `auxFn : function(){...}`

**Comment by tmedwards** [comment]
> Done, variables and aux functions moved into macro definition, took a bit of single player scrabble though because of the nuanced difference between `this.self` vs `this` in a `handler(...)` vs `auxFn : function(){...}`

Well the difference is simply that the `handler()` method is called with a `MacroContext` instance as it's `this`, but you likely didn't do the same with your helper methods.

You could easily do so in a number of ways:

* Using [`<Function>.call()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) or [`<Function>.apply()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) during invocation to set the function's `this`.  These are good for synchronous situations—e.g., direct calls.
* Using [`<Function>.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to create a copy of the function with `this` bound—more a wrapper, but the effect is the same.  This is good for asynchronous situations—e.g., `setTimeout()` callback—but also has its place in synchronous situations too.
* Using an arrow function wrapper, which automatically binds its scoped `this`, that then performs some shenanigans.
