### ISSUE TITLE
Carriage returns 

### ISSUE THREAD

**Issue by tmedwards** [SleepyFool-gh/Sleepy-macros#3]
https://github.com/SleepyFool-gh/Sleepy-macros/blob/1fe3103c00dce5ac44abc37708f0d0cca3fcd3f1/p-macro/p-macro.js#L9

You don't need to check for carriage returns (`\r`) in your regular expression as there won't be any in the passage text.  SugarCube strips all carriage returns as part of the decoding process.

**Comment by SleepyFool-gh** [comment]
Thanks, fixed!
